overrides:
  "@vite-hub/agent": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/agent@a99e853fc27c15195c9bb2ed467302c899cd900b"
  "@vite-hub/auth": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/auth@a99e853fc27c15195c9bb2ed467302c899cd900b"
  "@vite-hub/blob": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/blob@a99e853fc27c15195c9bb2ed467302c899cd900b"
  "@vite-hub/box": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/box@a99e853fc27c15195c9bb2ed467302c899cd900b"
  "@vite-hub/browser": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/browser@a99e853fc27c15195c9bb2ed467302c899cd900b"
  "@vite-hub/channels": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/channels@a99e853fc27c15195c9bb2ed467302c899cd900b"
  "@vite-hub/cli": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/cli@a99e853fc27c15195c9bb2ed467302c899cd900b"
  "@vite-hub/connections": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/connections@a99e853fc27c15195c9bb2ed467302c899cd900b"
  "@vite-hub/content": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/content@a99e853fc27c15195c9bb2ed467302c899cd900b"
  "@vite-hub/database": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/database@a99e853fc27c15195c9bb2ed467302c899cd900b"
  "@vite-hub/email": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/email@a99e853fc27c15195c9bb2ed467302c899cd900b"
  "@vite-hub/env": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/env@a99e853fc27c15195c9bb2ed467302c899cd900b"
  "@vite-hub/kv": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/kv@a99e853fc27c15195c9bb2ed467302c899cd900b"
  "@vite-hub/markdown-template": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/markdown-template@a99e853fc27c15195c9bb2ed467302c899cd900b"
  "@vite-hub/queue": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/queue@a99e853fc27c15195c9bb2ed467302c899cd900b"
  "@vite-hub/rate-limit": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/rate-limit@a99e853fc27c15195c9bb2ed467302c899cd900b"
  "@vite-hub/realtime": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/realtime@a99e853fc27c15195c9bb2ed467302c899cd900b"
  "@vite-hub/runtime": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/runtime@a99e853fc27c15195c9bb2ed467302c899cd900b"
  "@vite-hub/sandbox": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/sandbox@a99e853fc27c15195c9bb2ed467302c899cd900b"
  "@vite-hub/schedule": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/schedule@a99e853fc27c15195c9bb2ed467302c899cd900b"
  "@vite-hub/shell": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/shell@a99e853fc27c15195c9bb2ed467302c899cd900b"
  "@vite-hub/source": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/source@a99e853fc27c15195c9bb2ed467302c899cd900b"
  "@vite-hub/ui": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/ui@a99e853fc27c15195c9bb2ed467302c899cd900b"
  "@vite-hub/workflow": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/workflow@a99e853fc27c15195c9bb2ed467302c899cd900b"
  "@vite-hub/workspace": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/workspace@a99e853fc27c15195c9bb2ed467302c899cd900b"
