overrides:
  "@vite-hub/agent": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/agent@1bb5c5f95179b8984fe6918bd3c7866804a23b03"
  "@vite-hub/auth": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/auth@1bb5c5f95179b8984fe6918bd3c7866804a23b03"
  "@vite-hub/blob": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/blob@1bb5c5f95179b8984fe6918bd3c7866804a23b03"
  "@vite-hub/box": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/box@1bb5c5f95179b8984fe6918bd3c7866804a23b03"
  "@vite-hub/browser": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/browser@1bb5c5f95179b8984fe6918bd3c7866804a23b03"
  "@vite-hub/channels": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/channels@1bb5c5f95179b8984fe6918bd3c7866804a23b03"
  "@vite-hub/cli": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/cli@1bb5c5f95179b8984fe6918bd3c7866804a23b03"
  "@vite-hub/connections": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/connections@1bb5c5f95179b8984fe6918bd3c7866804a23b03"
  "@vite-hub/content": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/content@1bb5c5f95179b8984fe6918bd3c7866804a23b03"
  "@vite-hub/database": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/database@1bb5c5f95179b8984fe6918bd3c7866804a23b03"
  "@vite-hub/email": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/email@1bb5c5f95179b8984fe6918bd3c7866804a23b03"
  "@vite-hub/env": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/env@1bb5c5f95179b8984fe6918bd3c7866804a23b03"
  "@vite-hub/kv": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/kv@1bb5c5f95179b8984fe6918bd3c7866804a23b03"
  "@vite-hub/markdown-template": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/markdown-template@1bb5c5f95179b8984fe6918bd3c7866804a23b03"
  "@vite-hub/queue": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/queue@1bb5c5f95179b8984fe6918bd3c7866804a23b03"
  "@vite-hub/rate-limit": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/rate-limit@1bb5c5f95179b8984fe6918bd3c7866804a23b03"
  "@vite-hub/realtime": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/realtime@1bb5c5f95179b8984fe6918bd3c7866804a23b03"
  "@vite-hub/runtime": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/runtime@1bb5c5f95179b8984fe6918bd3c7866804a23b03"
  "@vite-hub/sandbox": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/sandbox@1bb5c5f95179b8984fe6918bd3c7866804a23b03"
  "@vite-hub/schedule": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/schedule@1bb5c5f95179b8984fe6918bd3c7866804a23b03"
  "@vite-hub/shell": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/shell@1bb5c5f95179b8984fe6918bd3c7866804a23b03"
  "@vite-hub/source": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/source@1bb5c5f95179b8984fe6918bd3c7866804a23b03"
  "@vite-hub/ui": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/ui@1bb5c5f95179b8984fe6918bd3c7866804a23b03"
  "@vite-hub/workflow": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/workflow@1bb5c5f95179b8984fe6918bd3c7866804a23b03"
  "@vite-hub/workspace": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/workspace@1bb5c5f95179b8984fe6918bd3c7866804a23b03"
