overrides:
  "@vite-hub/agent": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/agent@06d876950e1c76d3c6c166c88324d3ca229fef82"
  "@vite-hub/auth": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/auth@06d876950e1c76d3c6c166c88324d3ca229fef82"
  "@vite-hub/blob": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/blob@06d876950e1c76d3c6c166c88324d3ca229fef82"
  "@vite-hub/box": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/box@06d876950e1c76d3c6c166c88324d3ca229fef82"
  "@vite-hub/browser": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/browser@06d876950e1c76d3c6c166c88324d3ca229fef82"
  "@vite-hub/channels": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/channels@06d876950e1c76d3c6c166c88324d3ca229fef82"
  "@vite-hub/cli": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/cli@06d876950e1c76d3c6c166c88324d3ca229fef82"
  "@vite-hub/connections": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/connections@06d876950e1c76d3c6c166c88324d3ca229fef82"
  "@vite-hub/content": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/content@06d876950e1c76d3c6c166c88324d3ca229fef82"
  "@vite-hub/database": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/database@06d876950e1c76d3c6c166c88324d3ca229fef82"
  "@vite-hub/email": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/email@06d876950e1c76d3c6c166c88324d3ca229fef82"
  "@vite-hub/env": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/env@06d876950e1c76d3c6c166c88324d3ca229fef82"
  "@vite-hub/kv": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/kv@06d876950e1c76d3c6c166c88324d3ca229fef82"
  "@vite-hub/markdown-template": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/markdown-template@06d876950e1c76d3c6c166c88324d3ca229fef82"
  "@vite-hub/queue": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/queue@06d876950e1c76d3c6c166c88324d3ca229fef82"
  "@vite-hub/rate-limit": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/rate-limit@06d876950e1c76d3c6c166c88324d3ca229fef82"
  "@vite-hub/realtime": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/realtime@06d876950e1c76d3c6c166c88324d3ca229fef82"
  "@vite-hub/runtime": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/runtime@06d876950e1c76d3c6c166c88324d3ca229fef82"
  "@vite-hub/sandbox": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/sandbox@06d876950e1c76d3c6c166c88324d3ca229fef82"
  "@vite-hub/schedule": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/schedule@06d876950e1c76d3c6c166c88324d3ca229fef82"
  "@vite-hub/shell": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/shell@06d876950e1c76d3c6c166c88324d3ca229fef82"
  "@vite-hub/source": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/source@06d876950e1c76d3c6c166c88324d3ca229fef82"
  "@vite-hub/ui": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/ui@06d876950e1c76d3c6c166c88324d3ca229fef82"
  "@vite-hub/workflow": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/workflow@06d876950e1c76d3c6c166c88324d3ca229fef82"
  "@vite-hub/workspace": "https://pkg.pr.new/vite-hub/vitehub/@vite-hub/workspace@06d876950e1c76d3c6c166c88324d3ca229fef82"
