[Service]
Delegate=memory
DelegateSubgroup=controller
ProtectControlGroups=no
MemoryHigh=11G
MemoryMax=12G
MemorySwapMax=2G
Environment=BABYSITTER_WORKER_CGROUP_PARENT=/sys/fs/cgroup/system.slice/babysitter-vitehub.service
